version: '3'
services:
  web:
    build: './web'
    ports:
      - "3000:3000"

  pedido:
    build: './pedido'
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - ./pedido/pedido.env
    environment:
      - DB_HOST=mongodb://db/feiradafruta    
  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - pedido     
